Split out bootstrap

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,31 +1,24 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-command_exists () {
-    type "$1" &> /dev/null ;
-}
+# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
+# execute all executable files (excluding templates and editor backups) in the
+# ~/.config/yadm/bootstrap.d directory when run.
 
-if [[ -z "$SKIP_HOMEBREW" ]]; then
-  if ! command_exists brew; then
-      PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
-    if [[ "$CODESPACES" == "true" && -z "$SKIP_CACHE" ]]; then
-      sudo mkdir -p /home/linuxbrew/.linuxbrew
-      sudo chown --reference $HOME /home/linuxbrew/.linuxbrew
-      docker pull ghcr.io/claytono/linuxbrew-cache:latest
-      docker rm -f linuxbrew-cache || true
-      docker create --name linuxbrew-cache ghcr.io/claytono/linuxbrew-cache:latest true
-      docker cp linuxbrew-cache:/.linuxbrew /home/linuxbrew/
-      docker rm -f linuxbrew-cache || true
-      brew update
-    else
-      echo |/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+set -eu
+
+# Directory to look for bootstrap executables in
+BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+
+if [[ ! -d "$BOOTSTRAP_D" ]]; then
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    exit 1
+fi
+
+find "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+        if ! "$bootstrap"; then
+            echo "Error: bootstrap '$bootstrap' failed" >&2
+            exit 1
+        fi
     fi
-  fi
-
-
-  brew bundle install --no-lock --global
-fi
-
-if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
-  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
-  vim +PluginInstall +qall
-fi
+done
